/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../tsScripts/app/shared/search/apsearch.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '../../../../../tsScripts/app/services/category.service';
import * as import7 from '../../../../../tsScripts/app/services/question-answer.service';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/constants';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/http/src/http';
import * as import12 from '@angular/core/src/linker/component_factory_resolver';
import * as import13 from '@angular/router/src/router';
import * as import14 from '../../../../../tsScripts/app/services/communication.service';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from './search.css.shim.ngstyle';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '@angular/core/src/linker/view_container';
import * as import19 from '../../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import20 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import21 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import22 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import23 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import24 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import25 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import26 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import27 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '@angular/forms/src/directives/default_value_accessor';
import * as import30 from '@angular/forms/src/directives/validators';
import * as import31 from '@angular/forms/src/validators';
import * as import32 from '@angular/forms/src/directives/control_value_accessor';
import * as import33 from '@angular/forms/src/directives/ng_model';
import * as import34 from '@angular/forms/src/directives/ng_control';
import * as import35 from '@angular/forms/src/directives/ng_control_status';
import * as import36 from '@angular/common/src/directives/ng_if';
import * as import37 from '@angular/forms/src/directives/ng_form';
import * as import38 from '@angular/forms/src/directives/control_container';
import * as import39 from '@angular/common/src/directives/ng_class';
import * as import40 from '../../../../../tsScripts/app/shared/search/search-dropdown.component';
import * as import41 from './search-dropdown.component.ngfactory';
import * as import42 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import43 from '@angular/common/src/directives/ng_for';
export class Wrapper_ApSearchComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ApSearchComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  subscription0:any;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this._changed = false;
    this.context = new import0.ApSearchComponent(p0,p1,p2,p3,p4,p5);
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_placeBottom(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.placeBottom = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.onQuestionSubmit.subscribe(_eventHandler.bind(view,'onQuestionSubmit'))); }
  }
}
var renderType_ApSearchComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_ApSearchComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.ApSearchComponent>;
  _CategoryService_0_3:import6.CategoryService;
  _QuestionAnswerService_0_4:import7.QuestionAnswerService;
  _ApSearchComponent_0_5:Wrapper_ApSearchComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ApSearchComponent_Host0,renderType_ApSearchComponent_Host,import8.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ap-search',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ApSearchComponent0(this.viewUtils,this,0,this._el_0);
    this._CategoryService_0_3 = new import6.CategoryService(this.injectorGet(import11.Http,this.parentIndex));
    this._QuestionAnswerService_0_4 = new import7.QuestionAnswerService(this.injectorGet(import11.Http,this.parentIndex));
    this._ApSearchComponent_0_5 = new Wrapper_ApSearchComponent(this.injectorGet(import12.ComponentFactoryResolver,this.parentIndex),this.injectorGet(import13.Router,this.parentIndex),this._CategoryService_0_3,this._QuestionAnswerService_0_4,this.injectorGet(import14.CommunicationService,this.parentIndex),new import15.ElementRef(this._el_0));
    this.compView_0.create(this._ApSearchComponent_0_5.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import10.ComponentRef_<any>(0,this,this._el_0,this._ApSearchComponent_0_5.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import6.CategoryService) && (0 === requestNodeIndex))) { return this._CategoryService_0_3; }
    if (((token === import7.QuestionAnswerService) && (0 === requestNodeIndex))) { return this._QuestionAnswerService_0_4; }
    if (((token === import0.ApSearchComponent) && (0 === requestNodeIndex))) { return this._ApSearchComponent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ApSearchComponent_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._ApSearchComponent_0_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ApSearchComponentNgFactory:import10.ComponentFactory<import0.ApSearchComponent> = new import10.ComponentFactory<import0.ApSearchComponent>('ap-search',View_ApSearchComponent_Host0,import0.ApSearchComponent);
const styles_ApSearchComponent:any[] = [import16.styles];
var renderType_ApSearchComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_ApSearchComponent,{});
export class View_ApSearchComponent0 extends import2.AppView<import0.ApSearchComponent> {
  _viewQuery_ApSearchDropDownComponent_0:import17.QueryList<any>;
  _viewQuery_logginAnchor_1:import17.QueryList<any>;
  _el_0:any;
  /*private*/ _vc_0:import18.ViewContainer;
  _text_1:any;
  _el_2:any;
  _NgClass_2_3:import19.Wrapper_NgClass;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _NgForm_6_3:import20.Wrapper_NgForm;
  _ControlContainer_6_4:any;
  _NgControlStatusGroup_6_5:import21.Wrapper_NgControlStatusGroup;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _DefaultValueAccessor_10_3:import22.Wrapper_DefaultValueAccessor;
  _RequiredValidator_10_4:import23.Wrapper_RequiredValidator;
  _NG_VALIDATORS_10_5:any[];
  _NG_VALUE_ACCESSOR_10_6:any[];
  _NgModel_10_7:import24.Wrapper_NgModel;
  _NgControl_10_8:any;
  _NgControlStatus_10_9:import21.Wrapper_NgControlStatus;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _vc_22:import18.ViewContainer;
  _TemplateRef_22_5:any;
  _NgIf_22_6:import25.Wrapper_NgIf;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ApSearchComponent0,renderType_ApSearchComponent,import8.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways);
    this._expr_52 = import1.UNINITIALIZED;
    this._expr_53 = import1.UNINITIALIZED;
    this._expr_54 = import1.UNINITIALIZED;
    this._expr_55 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_ApSearchDropDownComponent_0 = new import17.QueryList<any>();
    this._viewQuery_logginAnchor_1 = new import17.QueryList<any>();
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_0 = new import18.ViewContainer(0,(null as any),this,this._el_0);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','search-xs','id','search-box'),(null as any));
    this._NgClass_2_3 = new import19.Wrapper_NgClass(this.parentView.injectorGet(import26.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import27.KeyValueDiffers,this.parentIndex),new import15.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray4(4,'class','center-width search-responsive','id','adv-search'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'form',new import3.InlineArray8(6,'class','z-header','id','search-panel','role','form'),(null as any));
    this._NgForm_6_3 = new import20.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_6_4 = this._NgForm_6_3.context;
    this._NgControlStatusGroup_6_5 = new import21.Wrapper_NgControlStatusGroup(this._ControlContainer_6_4);
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','icon-container'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'input',new import3.InlineArray16(14,'autocomplete','off','class','search-input fixed-height ','id','title','name','titleName','placeholder','Pregunta en Alta perspectiva','required','','type','text'),(null as any));
    this._DefaultValueAccessor_10_3 = new import22.Wrapper_DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_10));
    this._RequiredValidator_10_4 = new import23.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_10_5 = [this._RequiredValidator_10_4.context];
    this._NG_VALUE_ACCESSOR_10_6 = [this._DefaultValueAccessor_10_3.context];
    this._NgModel_10_7 = new import24.Wrapper_NgModel(this._ControlContainer_6_4,this._NG_VALIDATORS_10_5,(null as any),this._NG_VALUE_ACCESSOR_10_6);
    this._NgControl_10_8 = this._NgModel_10_7.context;
    this._NgControlStatus_10_9 = new import21.Wrapper_NgControlStatus(this._NgControl_10_8);
    this._text_11 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','question-begin'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'¿',(null as any));
    this._text_14 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray4(4,'class','question-end','id','question-end'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'?',(null as any));
    this._text_17 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray4(4,'id','temp-text','style','position:absolute;top:-100px; font-family:myriadpro-regular;font-size:15px;'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._text_21 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_22 = new import18.ViewContainer(22,6,this,this._anchor_22);
    this._TemplateRef_22_5 = new import28.TemplateRef_(this,22,this._anchor_22);
    this._NgIf_22_6 = new import25.Wrapper_NgIf(this._vc_22.vcRef,this._TemplateRef_22_5);
    this._text_23 = this.renderer.createText(this._el_6,'\n\n            ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_6,'button',new import3.InlineArray4(4,'class','ask-button fixed-height','type','submit'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-question-sign  visible-tab'),(null as any));
    this._text_27 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_24,'span',new import3.InlineArray2(2,'class','ask-text hidden-xs hidden-tab'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Preguntar',(null as any));
    this._text_31 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_2,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_6,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_6));
    this._NgForm_6_3.subscribe(this,this.eventHandler(this.handleEvent_6),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray16(12,'click',(null as any),'ngModelChange',(null as any),'keypress',(null as any),'keydown',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_10));
    this._NgModel_10_7.subscribe(this,this.eventHandler(this.handleEvent_10),true);
    this._viewQuery_logginAnchor_1.reset([this._vc_0.vcRef]);
    this.context.logginAnchor = this._viewQuery_logginAnchor_1.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import29.DefaultValueAccessor) && (10 === requestNodeIndex))) { return this._DefaultValueAccessor_10_3.context; }
    if (((token === import30.RequiredValidator) && (10 === requestNodeIndex))) { return this._RequiredValidator_10_4.context; }
    if (((token === import31.NG_VALIDATORS) && (10 === requestNodeIndex))) { return this._NG_VALIDATORS_10_5; }
    if (((token === import32.NG_VALUE_ACCESSOR) && (10 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_10_6; }
    if (((token === import33.NgModel) && (10 === requestNodeIndex))) { return this._NgModel_10_7.context; }
    if (((token === import34.NgControl) && (10 === requestNodeIndex))) { return this._NgControl_10_8; }
    if (((token === import35.NgControlStatus) && (10 === requestNodeIndex))) { return this._NgControlStatus_10_9.context; }
    if (((token === import28.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import36.NgIf) && (22 === requestNodeIndex))) { return this._NgIf_22_6.context; }
    if (((token === import37.NgForm) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgForm_6_3.context; }
    if (((token === import38.ControlContainer) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ControlContainer_6_4; }
    if (((token === import35.NgControlStatusGroup) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgControlStatusGroup_6_5.context; }
    if (((token === import39.NgClass) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._NgClass_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = 'search-xs';
    this._NgClass_2_3.check_klass(currVal_2_0_0,throwOnChange,false);
    const currVal_2_0_1:any = this.context.placeBottom;
    this._NgClass_2_3.check_ngClass(currVal_2_0_1,throwOnChange,false);
    this._NgClass_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgForm_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    this._NgControlStatusGroup_6_5.ngDoCheck(this,this._el_6,throwOnChange);
    this._DefaultValueAccessor_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_1_0:any = '';
    this._RequiredValidator_10_4.check_required(currVal_10_1_0,throwOnChange,false);
    this._RequiredValidator_10_4.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_2_0:any = 'titleName';
    this._NgModel_10_7.check_name(currVal_10_2_0,throwOnChange,false);
    const currVal_10_2_1:any = this.context.title;
    this._NgModel_10_7.check_model(currVal_10_2_1,throwOnChange,false);
    this._NgModel_10_7.ngDoCheck(this,this._el_10,throwOnChange);
    this._NgControlStatus_10_9.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_22_0_0:any = this.context.isOnModal;
    this._NgIf_22_6.check_ngIf(currVal_22_0_0,throwOnChange,false);
    this._NgIf_22_6.ngDoCheck(this,this._anchor_22,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
    this._vc_22.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_6_5.checkHost(this,this,this._el_6,throwOnChange);
    this._RequiredValidator_10_4.checkHost(this,this,this._el_10,throwOnChange);
    this._NgControlStatus_10_9.checkHost(this,this,this._el_10,throwOnChange);
    const currVal_52:boolean = !this.context.showQuestion;
    if (import3.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementProperty(this._el_12,'hidden',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:boolean = !this.context.showQuestion;
    if (import3.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementProperty(this._el_15,'hidden',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:any = import3.inlineInterpolate(1,'',this.context.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setText(this._text_19,currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:boolean = !this._NgModel_10_7.context.valid;
    if (import3.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setElementProperty(this._el_24,'disabled',currVal_55);
      this._expr_55 = currVal_55;
    }
    if (!throwOnChange) { if (this._viewQuery_ApSearchDropDownComponent_0.dirty) {
        this._viewQuery_ApSearchDropDownComponent_0.reset([this._vc_22.mapNestedViews(View_ApSearchComponent1,(nestedView:View_ApSearchComponent1):any => {
          return [nestedView._ApSearchDropDownComponent_3_5.context];
      })]);
      this.context.searchDropDown = this._viewQuery_ApSearchDropDownComponent_0.first;
    } }
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
    this._vc_22.destroyNestedViews();
    this._NgModel_10_7.ngOnDestroy();
    this._NgForm_6_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 22)) { return new View_ApSearchComponent1(this.viewUtils,this,22,this._anchor_22,this._vc_22); }
    return (null as any);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.handleClick($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_6(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_6_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.submitQuestion()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_10_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.showModal()) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'ngModelChange')) {
      const pd_sub_1:any = ((<any>this.context.movequestionMark($event)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'ngModelChange')) {
      const pd_sub_2:any = ((<any>(this.context.title = $event)) !== false);
      result = (pd_sub_2 && result);
    }
    if ((eventName == 'keypress')) {
      const pd_sub_3:any = ((<any>this.context.trimSpace($event)) !== false);
      result = (pd_sub_3 && result);
    }
    if ((eventName == 'keydown')) {
      const pd_sub_4:any = ((<any>this.context.filterQuestions($event)) !== false);
      result = (pd_sub_4 && result);
    }
    return result;
  }
}
class View_ApSearchComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  compView_3:import2.AppView<import40.ApSearchDropDownComponent>;
  _CategoryService_3_3:import6.CategoryService;
  _QuestionAnswerService_3_4:import7.QuestionAnswerService;
  _ApSearchDropDownComponent_3_5:import41.Wrapper_ApSearchDropDownComponent;
  _text_4:any;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _vc_6:import18.ViewContainer;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import25.Wrapper_NgIf;
  _text_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import18.ViewContainer) {
    super(View_ApSearchComponent1,renderType_ApSearchComponent,import8.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray4(4,'class','suggestions','id','suggestion'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_0,'search-dropdown',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_3 = new import41.View_ApSearchDropDownComponent0(this.viewUtils,this,3,this._el_3);
    this._CategoryService_3_3 = new import6.CategoryService(this.parentView.parentView.injectorGet(import11.Http,this.parentView.parentIndex));
    this._QuestionAnswerService_3_4 = new import7.QuestionAnswerService(this.parentView.parentView.injectorGet(import11.Http,this.parentView.parentIndex));
    this._ApSearchDropDownComponent_3_5 = new import41.Wrapper_ApSearchDropDownComponent(this.parentView.parentView.injectorGet(import13.Router,this.parentView.parentIndex),this._CategoryService_3_3,this._QuestionAnswerService_3_4);
    this.compView_3.create(this._ApSearchDropDownComponent_3_5.context);
    this._text_4 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_6 = new import18.ViewContainer(6,0,this,this._anchor_6);
    this._TemplateRef_6_5 = new import28.TemplateRef_(this,6,this._anchor_6);
    this._NgIf_6_6 = new import25.Wrapper_NgIf(this._vc_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._anchor_6,
      this._text_7
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import6.CategoryService) && (3 === requestNodeIndex))) { return this._CategoryService_3_3; }
    if (((token === import7.QuestionAnswerService) && (3 === requestNodeIndex))) { return this._QuestionAnswerService_3_4; }
    if (((token === import40.ApSearchDropDownComponent) && (3 === requestNodeIndex))) { return this._ApSearchDropDownComponent_3_5.context; }
    if (((token === import28.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import36.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3_0_0:any = this.parentView.context.title;
    this._ApSearchDropDownComponent_3_5.check_title(currVal_3_0_0,throwOnChange,false);
    const currVal_3_0_1:any = this.parentView.context.categories;
    this._ApSearchDropDownComponent_3_5.check_categories(currVal_3_0_1,throwOnChange,false);
    this._ApSearchDropDownComponent_3_5.ngDoCheck(this,this._el_3,throwOnChange);
    const currVal_6_0_0:any = ((((this.parentView.context.filteredQuestionList == null)? (null as any): this.parentView.context.filteredQuestionList.length) > 0) || (((this.parentView.context.categoryMatched == null)? (null as any): this.parentView.context.categoryMatched.length) > 0));
    this._NgIf_6_6.check_ngIf(currVal_6_0_0,throwOnChange,false);
    this._NgIf_6_6.ngDoCheck(this,this._anchor_6,throwOnChange);
    this._vc_6.detectChangesInNestedViews(throwOnChange);
    this.compView_3.internalDetectChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<View_ApSearchComponent0>this.parentView)._viewQuery_ApSearchDropDownComponent_0.setDirty();
  }
  destroyInternal():void {
    this._vc_6.destroyNestedViews();
    this.compView_3.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 6)) { return new View_ApSearchComponent2(this.viewUtils,this,6,this._anchor_6,this._vc_6); }
    return (null as any);
  }
}
class View_ApSearchComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _vc_6:import18.ViewContainer;
  _TemplateRef_6_5:any;
  _NgFor_6_6:import42.Wrapper_NgFor;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _el_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _el_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import18.ViewContainer) {
    super(View_ApSearchComponent2,renderType_ApSearchComponent,import8.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_32 = import1.UNINITIALIZED;
    this._expr_33 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','suggestion-container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','arrow-container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'ul',new import3.InlineArray2(2,'class','question-List'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_6 = new import18.ViewContainer(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import28.TemplateRef_(this,6,this._anchor_6);
    this._NgFor_6_6 = new import42.Wrapper_NgFor(this._vc_6.vcRef,this._TemplateRef_6_5,this.parentView.parentView.parentView.injectorGet(import26.IterableDiffers,this.parentView.parentView.parentIndex),this.parentView.parentView.ref);
    this._text_7 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_4,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                            ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_10,'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-search topic-icon'),(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'span',new import3.InlineArray2(2,'class','search-footer'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Etapa de tu negocio:',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n                            ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_8,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_17 = this.renderer.createText(this._el_8,'\n                        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_4,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n                            ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_21,'span',new import3.InlineArray4(4,'aria-hidden','true','class','glyphicon glyphicon-search topic-icon'),(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'span',new import3.InlineArray2(2,'class','search-footer'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Buscar:',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'',(null as any));
    this._text_26 = this.renderer.createText(this._el_19,'\n                        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._el_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import43.NgFor) && (6 === requestNodeIndex))) { return this._NgFor_6_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_6_0_0:any = this.parentView.parentView.context.filteredQuestionList;
    this._NgFor_6_6.check_ngForOf(currVal_6_0_0,throwOnChange,false);
    this._NgFor_6_6.ngDoCheck(this,this._anchor_6,throwOnChange);
    this._vc_6.detectChangesInNestedViews(throwOnChange);
    const currVal_32:any = import3.inlineInterpolate(1,'  ',this.parentView.parentView.context.categoryMatched,'');
    if (import3.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setText(this._text_14,currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = import3.inlineInterpolate(1,'  ',(this.parentView.parentView.context.title? (this.parentView.parentView.context.title + '?'): ''),'');
    if (import3.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setText(this._text_25,currVal_33);
      this._expr_33 = currVal_33;
    }
  }
  destroyInternal():void {
    this._vc_6.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 6)) { return new View_ApSearchComponent3(this.viewUtils,this,6,this._anchor_6,this._vc_6); }
    return (null as any);
  }
}
class View_ApSearchComponent3 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import18.ViewContainer) {
    super(View_ApSearchComponent3,renderType_ApSearchComponent,import8.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_7 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7:any = import3.inlineInterpolate(1,'',this.context.$implicit.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_3,currVal_7);
      this._expr_7 = currVal_7;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.parentView.context.selectQuestionDetails(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}