/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './question-details.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '../../services/resolve.services/question.resolver';
import * as import6 from '../../services/question-answer.service';
import * as import7 from '../../services/authentication.service';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/constants';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/http/src/http';
import * as import12 from '@angular/router/src/router';
import * as import13 from '@angular/router/src/router_state';
import * as import14 from '@angular/core/src/linker/component_factory_resolver';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '@angular/core/src/linker/view_container';
import * as import17 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import18 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import19 from '../../shared/left-menu/related-question-left-menu.component';
import * as import20 from '../../services/category.service';
import * as import21 from '../../shared/left-menu/related-question-left-menu.component.ngfactory';
import * as import22 from '../../shared/left-menu/related-topic.component';
import * as import23 from '../../services/question.service';
import * as import24 from '../../shared/left-menu/related-topic.component.ngfactory';
import * as import25 from '../../shared/left-menu/category-left-menu.component';
import * as import26 from '../../shared/left-menu/category-left-menu.component.ngfactory';
import * as import27 from '@angular/common/src/location/location_strategy';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '../../services/communication.service';
import * as import30 from '@angular/router/src/directives/router_link';
import * as import31 from '@angular/common/src/directives/ng_if';
import * as import32 from '../../shared/question-header/question-header.component';
import * as import33 from '../../shared/question-header/question-header.component.ngfactory';
import * as import34 from '../../shared/user-info/user-info.component';
import * as import35 from '../../services/profile.service';
import * as import36 from '../../shared/user-info/user-info.component.ngfactory';
import * as import37 from '../../shared/status/status.component';
import * as import38 from '../../services/status.service';
import * as import39 from '../../shared/status/status.component.ngfactory';
import * as import40 from '../../shared/comment/comment.component';
import * as import41 from '../../services/comment.service';
import * as import42 from '../../shared/comment/comment.component.ngfactory';
import * as import43 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import44 from '@angular/core/src/change_detection/change_detection_util';
import * as import45 from 'ng2-toastr/src/toast-manager';
import * as import46 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import47 from '@angular/common/src/directives/ng_for';
import * as import48 from '@angular/core/src/security';
import * as import49 from '../../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import50 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import51 from '@angular/core/src/linker/element_ref';
import * as import52 from '@angular/common/src/directives/ng_class';
import * as import53 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import54 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import55 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import56 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import57 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import58 from '@angular/forms/src/directives/default_value_accessor';
import * as import59 from '@angular/forms/src/directives/validators';
import * as import60 from '@angular/forms/src/validators';
import * as import61 from '@angular/forms/src/directives/control_value_accessor';
import * as import62 from '@angular/forms/src/directives/ng_model';
import * as import63 from '@angular/forms/src/directives/ng_control';
import * as import64 from '@angular/forms/src/directives/ng_control_status';
import * as import65 from '@angular/forms/src/directives/ng_form';
import * as import66 from '@angular/forms/src/directives/control_container';
export class Wrapper_QuestionDetailComponent {
  /*private*/ _eventHandler:Function;
  context:import0.QuestionDetailComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this._changed = false;
    this.context = new import0.QuestionDetailComponent(p0,p1,p2,p3,p4,p5);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_QuestionDetailComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_QuestionDetailComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.QuestionDetailComponent>;
  _QuestionResolver_0_3:import5.QuestionResolver;
  _QuestionAnswerService_0_4:import6.QuestionAnswerService;
  _AuthenticationService_0_5:import7.AuthenticationService;
  _QuestionDetailComponent_0_6:Wrapper_QuestionDetailComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_QuestionDetailComponent_Host0,renderType_QuestionDetailComponent_Host,import8.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'question-details',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_QuestionDetailComponent0(this.viewUtils,this,0,this._el_0);
    this._QuestionResolver_0_3 = new import5.QuestionResolver(this.injectorGet(import11.Http,this.parentIndex));
    this._QuestionAnswerService_0_4 = new import6.QuestionAnswerService(this.injectorGet(import11.Http,this.parentIndex));
    this._AuthenticationService_0_5 = new import7.AuthenticationService(this.injectorGet(import11.Http,this.parentIndex));
    this._QuestionDetailComponent_0_6 = new Wrapper_QuestionDetailComponent(this.injectorGet(import12.Router,this.parentIndex),this.injectorGet(import13.ActivatedRoute,this.parentIndex),this._QuestionResolver_0_3,this._QuestionAnswerService_0_4,this._AuthenticationService_0_5,this.injectorGet(import14.ComponentFactoryResolver,this.parentIndex));
    this.compView_0.create(this._QuestionDetailComponent_0_6.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import10.ComponentRef_<any>(0,this,this._el_0,this._QuestionDetailComponent_0_6.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.QuestionResolver) && (0 === requestNodeIndex))) { return this._QuestionResolver_0_3; }
    if (((token === import6.QuestionAnswerService) && (0 === requestNodeIndex))) { return this._QuestionAnswerService_0_4; }
    if (((token === import7.AuthenticationService) && (0 === requestNodeIndex))) { return this._AuthenticationService_0_5; }
    if (((token === import0.QuestionDetailComponent) && (0 === requestNodeIndex))) { return this._QuestionDetailComponent_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._QuestionDetailComponent_0_6.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const QuestionDetailComponentNgFactory:import10.ComponentFactory<import0.QuestionDetailComponent> = new import10.ComponentFactory<import0.QuestionDetailComponent>('question-details',View_QuestionDetailComponent_Host0,import0.QuestionDetailComponent);
const styles_QuestionDetailComponent:any[] = ['.disabledFollowingImg[_ngcontent-%COMP%] {\n        height: 25px;\n        opacity: .1;\n    }\n\n    .enableFollowingImg[_ngcontent-%COMP%] {\n        height: 25px;\n        opacity: 1;\n    }\n\n        .enableFollowingImg[_ngcontent-%COMP%]:hover {\n            height: 30px;\n        }\n\n    .filter-panel[_ngcontent-%COMP%] {\n        margin-left: 2px;\n        margin-right: 15px;\n    }'];
var renderType_QuestionDetailComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_QuestionDetailComponent,{});
export class View_QuestionDetailComponent0 extends import1.AppView<import0.QuestionDetailComponent> {
  _viewQuery_answerAnchor_0:import15.QueryList<any>;
  _viewQuery_questionReport_1:import15.QueryList<any>;
  _viewQuery_logginAnchor_2:import15.QueryList<any>;
  _text_0:any;
  _el_1:any;
  /*private*/ _vc_1:import16.ViewContainer;
  _text_2:any;
  _el_3:any;
  /*private*/ _vc_3:import16.ViewContainer;
  _text_4:any;
  _el_5:any;
  /*private*/ _vc_5:import16.ViewContainer;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _el_22:any;
  _RouterLinkWithHref_22_3:import17.Wrapper_RouterLinkWithHref;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _el_26:any;
  _RouterLinkWithHref_26_3:import17.Wrapper_RouterLinkWithHref;
  _text_27:any;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _vc_29:import16.ViewContainer;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import18.Wrapper_NgIf;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _vc_31:import16.ViewContainer;
  _TemplateRef_31_5:any;
  _NgIf_31_6:import18.Wrapper_NgIf;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _vc_33:import16.ViewContainer;
  _TemplateRef_33_5:any;
  _NgIf_33_6:import18.Wrapper_NgIf;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _vc_35:import16.ViewContainer;
  _TemplateRef_35_5:any;
  _NgIf_35_6:import18.Wrapper_NgIf;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  compView_39:import1.AppView<import19.RelatedQuestionMenu>;
  _QuestionAnswerService_39_3:import6.QuestionAnswerService;
  _CategoryService_39_4:import20.CategoryService;
  _RelatedQuestionMenu_39_5:import21.Wrapper_RelatedQuestionMenu;
  _text_40:any;
  _el_41:any;
  compView_41:import1.AppView<import22.RelatedTopicComponent>;
  _QuestionService_41_3:import23.QuestionService;
  _RelatedTopicComponent_41_4:import24.Wrapper_RelatedTopicComponent;
  _text_42:any;
  _el_43:any;
  compView_43:import1.AppView<import25.CategoryMenuPanelComponent>;
  _QuestionAnswerService_43_3:import6.QuestionAnswerService;
  _CategoryService_43_4:import20.CategoryService;
  _CategoryMenuPanelComponent_43_5:import26.Wrapper_CategoryMenuPanelComponent;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _anchor_47:any;
  /*private*/ _vc_47:import16.ViewContainer;
  _TemplateRef_47_5:any;
  _NgIf_47_6:import18.Wrapper_NgIf;
  _text_48:any;
  _anchor_49:any;
  /*private*/ _vc_49:import16.ViewContainer;
  _TemplateRef_49_5:any;
  _NgIf_49_6:import18.Wrapper_NgIf;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_QuestionDetailComponent0,renderType_QuestionDetailComponent,import8.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_answerAnchor_0 = new import15.QueryList<any>();
    this._viewQuery_questionReport_1 = new import15.QueryList<any>();
    this._viewQuery_logginAnchor_2 = new import15.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_1 = new import16.ViewContainer(1,(null as any),this,this._el_1);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_3 = new import16.ViewContainer(3,(null as any),this,this._el_3);
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_5 = new import16.ViewContainer(5,(null as any),this,this._el_5);
    this._text_6 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','left-panel category-panel-xs','id','toggleMenu'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','menu-container visible-xs'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','cloe-button'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,' ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'i',new import3.InlineArray2(2,'class','fa fa-arrow-left'),(null as any));
    this._text_16 = this.renderer.createText(this._el_13,' ',(null as any));
    this._text_17 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_9,'ul',new import3.InlineArray2(2,'class','left-panel-list'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'li',new import3.InlineArray2(2,'class',''),(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_21,'a',new import3.InlineArray2(2,'routerLink','/'),(null as any));
    this._RouterLinkWithHref_22_3 = new import17.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import12.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import27.LocationStrategy,this.parentIndex));
    this._text_23 = this.renderer.createText(this._el_22,'Alta Perspectiva',(null as any));
    this._text_24 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_19,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_25,'a',new import3.InlineArray2(2,'routerLink','/question/home/1'),(null as any));
    this._RouterLinkWithHref_26_3 = new import17.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import12.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import27.LocationStrategy,this.parentIndex));
    this._text_27 = this.renderer.createText(this._el_26,'Preguntas',(null as any));
    this._text_28 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_29 = new import16.ViewContainer(29,19,this,this._anchor_29);
    this._TemplateRef_29_5 = new import28.TemplateRef_(this,29,this._anchor_29);
    this._NgIf_29_6 = new import18.Wrapper_NgIf(this._vc_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._anchor_31 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_31 = new import16.ViewContainer(31,19,this,this._anchor_31);
    this._TemplateRef_31_5 = new import28.TemplateRef_(this,31,this._anchor_31);
    this._NgIf_31_6 = new import18.Wrapper_NgIf(this._vc_31.vcRef,this._TemplateRef_31_5);
    this._text_32 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_33 = new import16.ViewContainer(33,19,this,this._anchor_33);
    this._TemplateRef_33_5 = new import28.TemplateRef_(this,33,this._anchor_33);
    this._NgIf_33_6 = new import18.Wrapper_NgIf(this._vc_33.vcRef,this._TemplateRef_33_5);
    this._text_34 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_35 = new import16.ViewContainer(35,19,this,this._anchor_35);
    this._TemplateRef_35_5 = new import28.TemplateRef_(this,35,this._anchor_35);
    this._NgIf_35_6 = new import18.Wrapper_NgIf(this._vc_35.vcRef,this._TemplateRef_35_5);
    this._text_36 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._text_37 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_38 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_7,'related-question-left-menu',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_39 = new import21.View_RelatedQuestionMenu0(this.viewUtils,this,39,this._el_39);
    this._QuestionAnswerService_39_3 = new import6.QuestionAnswerService(this.parentView.injectorGet(import11.Http,this.parentIndex));
    this._CategoryService_39_4 = new import20.CategoryService(this.parentView.injectorGet(import11.Http,this.parentIndex));
    this._RelatedQuestionMenu_39_5 = new import21.Wrapper_RelatedQuestionMenu(this._QuestionAnswerService_39_3,this._CategoryService_39_4,this.parentView.injectorGet(import12.Router,this.parentIndex),this.parentView.injectorGet(import13.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import29.CommunicationService,this.parentIndex));
    this.compView_39.create(this._RelatedQuestionMenu_39_5.context);
    this._text_40 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_7,'related-topic',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_41 = new import24.View_RelatedTopicComponent0(this.viewUtils,this,41,this._el_41);
    this._QuestionService_41_3 = new import23.QuestionService(this.parentView.injectorGet(import11.Http,this.parentIndex));
    this._RelatedTopicComponent_41_4 = new import24.Wrapper_RelatedTopicComponent(this._QuestionService_41_3,this.parentView.injectorGet(import29.CommunicationService,this.parentIndex));
    this.compView_41.create(this._RelatedTopicComponent_41_4.context);
    this._text_42 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_7,'category-left-menu',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_43 = new import26.View_CategoryMenuPanelComponent0(this.viewUtils,this,43,this._el_43);
    this._QuestionAnswerService_43_3 = new import6.QuestionAnswerService(this.parentView.injectorGet(import11.Http,this.parentIndex));
    this._CategoryService_43_4 = new import20.CategoryService(this.parentView.injectorGet(import11.Http,this.parentIndex));
    this._CategoryMenuPanelComponent_43_5 = new import26.Wrapper_CategoryMenuPanelComponent(this._QuestionAnswerService_43_3,this._CategoryService_43_4,this.parentView.injectorGet(import29.CommunicationService,this.parentIndex));
    this.compView_43.create(this._CategoryMenuPanelComponent_43_5.context);
    this._text_44 = this.renderer.createText(this._el_7,'\n',(null as any));
    this._text_45 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_46 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_47 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_47 = new import16.ViewContainer(47,(null as any),this,this._anchor_47);
    this._TemplateRef_47_5 = new import28.TemplateRef_(this,47,this._anchor_47);
    this._NgIf_47_6 = new import18.Wrapper_NgIf(this._vc_47.vcRef,this._TemplateRef_47_5);
    this._text_48 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_49 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_49 = new import16.ViewContainer(49,(null as any),this,this._anchor_49);
    this._TemplateRef_49_5 = new import28.TemplateRef_(this,49,this._anchor_49);
    this._NgIf_49_6 = new import18.Wrapper_NgIf(this._vc_49.vcRef,this._TemplateRef_49_5);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_13,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_13));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_22,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_22));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_26,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_26));
    this._viewQuery_answerAnchor_0.reset([this._vc_1.vcRef]);
    this.context.answerAnchor = this._viewQuery_answerAnchor_0.first;
    this._viewQuery_questionReport_1.reset([this._vc_3.vcRef]);
    this.context.questionReport = this._viewQuery_questionReport_1.first;
    this._viewQuery_logginAnchor_2.reset([this._vc_5.vcRef]);
    this.context.logginAnchor = this._viewQuery_logginAnchor_2.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._anchor_47,
      this._text_48,
      this._anchor_49
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import30.RouterLinkWithHref) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._RouterLinkWithHref_22_3.context; }
    if (((token === import30.RouterLinkWithHref) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._RouterLinkWithHref_26_3.context; }
    if (((token === import28.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import31.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6.context; }
    if (((token === import28.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import31.NgIf) && (31 === requestNodeIndex))) { return this._NgIf_31_6.context; }
    if (((token === import28.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import31.NgIf) && (33 === requestNodeIndex))) { return this._NgIf_33_6.context; }
    if (((token === import28.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import31.NgIf) && (35 === requestNodeIndex))) { return this._NgIf_35_6.context; }
    if (((token === import6.QuestionAnswerService) && (39 === requestNodeIndex))) { return this._QuestionAnswerService_39_3; }
    if (((token === import20.CategoryService) && (39 === requestNodeIndex))) { return this._CategoryService_39_4; }
    if (((token === import19.RelatedQuestionMenu) && (39 === requestNodeIndex))) { return this._RelatedQuestionMenu_39_5.context; }
    if (((token === import23.QuestionService) && (41 === requestNodeIndex))) { return this._QuestionService_41_3; }
    if (((token === import22.RelatedTopicComponent) && (41 === requestNodeIndex))) { return this._RelatedTopicComponent_41_4.context; }
    if (((token === import6.QuestionAnswerService) && (43 === requestNodeIndex))) { return this._QuestionAnswerService_43_3; }
    if (((token === import20.CategoryService) && (43 === requestNodeIndex))) { return this._CategoryService_43_4; }
    if (((token === import25.CategoryMenuPanelComponent) && (43 === requestNodeIndex))) { return this._CategoryMenuPanelComponent_43_5.context; }
    if (((token === import28.TemplateRef) && (47 === requestNodeIndex))) { return this._TemplateRef_47_5; }
    if (((token === import31.NgIf) && (47 === requestNodeIndex))) { return this._NgIf_47_6.context; }
    if (((token === import28.TemplateRef) && (49 === requestNodeIndex))) { return this._TemplateRef_49_5; }
    if (((token === import31.NgIf) && (49 === requestNodeIndex))) { return this._NgIf_49_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_22_0_0:any = '/';
    this._RouterLinkWithHref_22_3.check_routerLink(currVal_22_0_0,throwOnChange,false);
    this._RouterLinkWithHref_22_3.ngDoCheck(this,this._el_22,throwOnChange);
    const currVal_26_0_0:any = '/question/home/1';
    this._RouterLinkWithHref_26_3.check_routerLink(currVal_26_0_0,throwOnChange,false);
    this._RouterLinkWithHref_26_3.ngDoCheck(this,this._el_26,throwOnChange);
    const currVal_29_0_0:any = this.context._logObj.isLoggedIn;
    this._NgIf_29_6.check_ngIf(currVal_29_0_0,throwOnChange,false);
    this._NgIf_29_6.ngDoCheck(this,this._anchor_29,throwOnChange);
    const currVal_31_0_0:any = this.context._logObj.isLoggedIn;
    this._NgIf_31_6.check_ngIf(currVal_31_0_0,throwOnChange,false);
    this._NgIf_31_6.ngDoCheck(this,this._anchor_31,throwOnChange);
    const currVal_33_0_0:boolean = !this.context._logObj.isLoggedIn;
    this._NgIf_33_6.check_ngIf(currVal_33_0_0,throwOnChange,false);
    this._NgIf_33_6.ngDoCheck(this,this._anchor_33,throwOnChange);
    const currVal_35_0_0:boolean = !this.context._logObj.isLoggedIn;
    this._NgIf_35_6.check_ngIf(currVal_35_0_0,throwOnChange,false);
    this._NgIf_35_6.ngDoCheck(this,this._anchor_35,throwOnChange);
    this._RelatedQuestionMenu_39_5.ngDoCheck(this,this._el_39,throwOnChange);
    const currVal_41_0_0:any = ((this.context.question == null)? (null as any): ((this.context.question.questionTopics[0] == null)? (null as any): this.context.question.questionTopics[0].topicId));
    this._RelatedTopicComponent_41_4.check_topicId(currVal_41_0_0,throwOnChange,false);
    this._RelatedTopicComponent_41_4.ngDoCheck(this,this._el_41,throwOnChange);
    const currVal_43_0_0:any = ((this.context.question == null)? (null as any): ((this.context.question.categories[0] == null)? (null as any): this.context.question.categories[0].id));
    this._CategoryMenuPanelComponent_43_5.check_caegoryId(currVal_43_0_0,throwOnChange,false);
    this._CategoryMenuPanelComponent_43_5.ngDoCheck(this,this._el_43,throwOnChange);
    const currVal_47_0_0:boolean = !this.context.showQuestionEditForm;
    this._NgIf_47_6.check_ngIf(currVal_47_0_0,throwOnChange,false);
    this._NgIf_47_6.ngDoCheck(this,this._anchor_47,throwOnChange);
    const currVal_49_0_0:any = this.context.showQuestionEditForm;
    this._NgIf_49_6.check_ngIf(currVal_49_0_0,throwOnChange,false);
    this._NgIf_49_6.ngDoCheck(this,this._anchor_49,throwOnChange);
    this._vc_1.detectChangesInNestedViews(throwOnChange);
    this._vc_3.detectChangesInNestedViews(throwOnChange);
    this._vc_5.detectChangesInNestedViews(throwOnChange);
    this._vc_29.detectChangesInNestedViews(throwOnChange);
    this._vc_31.detectChangesInNestedViews(throwOnChange);
    this._vc_33.detectChangesInNestedViews(throwOnChange);
    this._vc_35.detectChangesInNestedViews(throwOnChange);
    this._vc_47.detectChangesInNestedViews(throwOnChange);
    this._vc_49.detectChangesInNestedViews(throwOnChange);
    this._RouterLinkWithHref_22_3.checkHost(this,this,this._el_22,throwOnChange);
    this._RouterLinkWithHref_26_3.checkHost(this,this,this._el_26,throwOnChange);
    this.compView_39.internalDetectChanges(throwOnChange);
    this.compView_41.internalDetectChanges(throwOnChange);
    this.compView_43.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_1.destroyNestedViews();
    this._vc_3.destroyNestedViews();
    this._vc_5.destroyNestedViews();
    this._vc_29.destroyNestedViews();
    this._vc_31.destroyNestedViews();
    this._vc_33.destroyNestedViews();
    this._vc_35.destroyNestedViews();
    this._vc_47.destroyNestedViews();
    this._vc_49.destroyNestedViews();
    this.compView_39.destroy();
    this.compView_41.destroy();
    this.compView_43.destroy();
    this._RouterLinkWithHref_22_3.ngOnDestroy();
    this._RouterLinkWithHref_26_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 29)) { return new View_QuestionDetailComponent1(this.viewUtils,this,29,this._anchor_29,this._vc_29); }
    if ((nodeIndex == 31)) { return new View_QuestionDetailComponent2(this.viewUtils,this,31,this._anchor_31,this._vc_31); }
    if ((nodeIndex == 33)) { return new View_QuestionDetailComponent3(this.viewUtils,this,33,this._anchor_33,this._vc_33); }
    if ((nodeIndex == 35)) { return new View_QuestionDetailComponent4(this.viewUtils,this,35,this._anchor_35,this._vc_35); }
    if ((nodeIndex == 47)) { return new View_QuestionDetailComponent5(this.viewUtils,this,47,this._anchor_47,this._vc_47); }
    if ((nodeIndex == 49)) { return new View_QuestionDetailComponent8(this.viewUtils,this,49,this._anchor_49,this._vc_49); }
    return (null as any);
  }
  handleEvent_13(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.hideMenu()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_22(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_22_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_26(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_26_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_QuestionDetailComponent1 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_QuestionDetailComponent1,renderType_QuestionDetailComponent,import8.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,' Perfil',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.gotoProfile()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_QuestionDetailComponent2 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_QuestionDetailComponent2,renderType_QuestionDetailComponent,import8.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','/signout'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,' Cerrar sesión ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_QuestionDetailComponent3 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_QuestionDetailComponent3,renderType_QuestionDetailComponent,import8.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','/signin'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Iniciar sesión',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_QuestionDetailComponent4 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_QuestionDetailComponent4,renderType_QuestionDetailComponent,import8.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'href','/signin'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Regístrate ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_QuestionDetailComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import32.QuestionHeaderComponent>;
  _QuestionHeaderComponent_4_3:import33.Wrapper_QuestionHeaderComponent;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  compView_11:import1.AppView<import34.UserInfoComponent>;
  _ProfileService_11_3:import35.ProfileService;
  _UserInfoComponent_11_4:import36.Wrapper_UserInfoComponent;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  compView_15:import1.AppView<import37.StatusComponent>;
  _StatusService_15_3:import38.StatusService;
  _QuestionService_15_4:import23.QuestionService;
  _StatusComponent_15_5:import39.Wrapper_StatusComponent;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  compView_18:import1.AppView<import40.CommentComponent>;
  _CommentService_18_3:import41.CommentService;
  _CommentComponent_18_4:import42.Wrapper_CommentComponent;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _anchor_61:any;
  /*private*/ _vc_61:import16.ViewContainer;
  _TemplateRef_61_5:any;
  _NgFor_61_6:import43.Wrapper_NgFor;
  _text_62:any;
  _text_63:any;
  /*private*/ _expr_79:any;
  /*private*/ _expr_80:any;
  /*private*/ _expr_81:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_QuestionDetailComponent5,renderType_QuestionDetailComponent,import8.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_79 = import44.UNINITIALIZED;
    this._expr_80 = import44.UNINITIALIZED;
    this._expr_81 = import44.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','center-width center-fix center-body z-ground'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'question-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import33.View_QuestionHeaderComponent0(this.viewUtils,this,4,this._el_4);
    this._QuestionHeaderComponent_4_3 = new import33.Wrapper_QuestionHeaderComponent(this.parentView.injectorGet(import12.Router,this.parentIndex));
    this.compView_4.create(this._QuestionHeaderComponent_4_3.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'h1',new import3.InlineArray2(2,'class','question-title'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','article-details'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'user-info',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_11 = new import36.View_UserInfoComponent0(this.viewUtils,this,11,this._el_11);
    this._ProfileService_11_3 = new import35.ProfileService(this.parentView.injectorGet(import11.Http,this.parentIndex));
    this._UserInfoComponent_11_4 = new import36.Wrapper_UserInfoComponent(this._ProfileService_11_3);
    this.compView_11.create(this._UserInfoComponent_11_4.context);
    this._text_12 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_9,'p',new import3.InlineArray2(2,'class','answer-text'),(null as any));
    this._text_14 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_9,'ap-status',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_15 = new import39.View_StatusComponent0(this.viewUtils,this,15,this._el_15);
    this._StatusService_15_3 = new import38.StatusService(this.parentView.injectorGet(import11.Http,this.parentIndex));
    this._QuestionService_15_4 = new import23.QuestionService(this.parentView.injectorGet(import11.Http,this.parentIndex));
    this._StatusComponent_15_5 = new import39.Wrapper_StatusComponent(this.parentView.injectorGet(import14.ComponentFactoryResolver,this.parentIndex),this.parentView.injectorGet(import7.AuthenticationService,this.parentIndex),this._StatusService_15_3,this.parentView.injectorGet(import6.QuestionAnswerService,this.parentIndex),this.parentView.injectorGet(import29.CommunicationService,this.parentIndex),this._QuestionService_15_4,this.parentView.injectorGet(import45.ToastsManager,this.parentIndex));
    this._text_16 = this.renderer.createText((null as any),' ',(null as any));
    this.compView_15.create(this._StatusComponent_15_5.context);
    this._text_17 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_9,'ap-comment',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_18 = new import42.View_CommentComponent0(this.viewUtils,this,18,this._el_18);
    this._CommentService_18_3 = new import41.CommentService(this.parentView.injectorGet(import11.Http,this.parentIndex));
    this._CommentComponent_18_4 = new import42.Wrapper_CommentComponent(this._CommentService_18_3,this.parentView.injectorGet(import14.ComponentFactoryResolver,this.parentIndex),this.parentView.injectorGet(import29.CommunicationService,this.parentIndex));
    this.compView_18.create(this._CommentComponent_18_4.context);
    this._text_19 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_20 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_2,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_2,'button',new import3.InlineArray2(2,'class','answer-button'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._text_25 = this.renderer.createText(this._el_23,'\n            Responder\n        ',(null as any));
    this._text_26 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','summery-panel'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n            ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'',(null as any));
    this._text_31 = this.renderer.createText(this._el_29,'Respuestas\n            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_27,'\n            ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_27,'div',new import3.InlineArray2(2,'class','row filter-panel'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'\n                        ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_37,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n                            ',(null as any));
    this._text_41 = this.renderer.createText(this._el_39,'\n                            Últimas respuestas\n                        ',(null as any));
    this._text_42 = this.renderer.createText(this._el_37,'\n                    ',(null as any));
    this._text_43 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._text_44 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_33,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n                    ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_45,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n                        ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_47,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'\n                            ',(null as any));
    this._text_51 = this.renderer.createText(this._el_49,'\n                            Mejores respuestas\n                        ',(null as any));
    this._text_52 = this.renderer.createText(this._el_47,'\n                    ',(null as any));
    this._text_53 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._text_54 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._text_55 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._text_56 = this.renderer.createText(this._el_27,'\n            ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_27,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_58 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._text_59 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._text_60 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._anchor_61 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_61 = new import16.ViewContainer(61,2,this,this._anchor_61);
    this._TemplateRef_61_5 = new import28.TemplateRef_(this,61,this._anchor_61);
    this._NgFor_61_6 = new import43.Wrapper_NgFor(this._vc_61.vcRef,this._TemplateRef_61_5,this.parentView.injectorGet(import46.IterableDiffers,this.parentIndex),this.parentView.ref);
    this._text_62 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_63 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray4(4,'onQuestionDetailClicked',(null as any),'onQuestionReportClicked',(null as any)),this.eventHandler(this.handleEvent_15));
    this._StatusComponent_15_5.subscribe(this,this.eventHandler(this.handleEvent_15),true,true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_23));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_37,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_37));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_47,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_47));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._anchor_61,
      this._text_62,
      this._text_63
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.QuestionHeaderComponent) && (4 === requestNodeIndex))) { return this._QuestionHeaderComponent_4_3.context; }
    if (((token === import35.ProfileService) && (11 === requestNodeIndex))) { return this._ProfileService_11_3; }
    if (((token === import34.UserInfoComponent) && (11 === requestNodeIndex))) { return this._UserInfoComponent_11_4.context; }
    if (((token === import38.StatusService) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._StatusService_15_3; }
    if (((token === import23.QuestionService) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._QuestionService_15_4; }
    if (((token === import37.StatusComponent) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._StatusComponent_15_5.context; }
    if (((token === import41.CommentService) && (18 === requestNodeIndex))) { return this._CommentService_18_3; }
    if (((token === import40.CommentComponent) && (18 === requestNodeIndex))) { return this._CommentComponent_18_4.context; }
    if (((token === import28.TemplateRef) && (61 === requestNodeIndex))) { return this._TemplateRef_61_5; }
    if (((token === import47.NgFor) && (61 === requestNodeIndex))) { return this._NgFor_61_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4_0_0:any = this.parentView.context.question;
    this._QuestionHeaderComponent_4_3.check_question(currVal_4_0_0,throwOnChange,false);
    this._QuestionHeaderComponent_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_11_0_0:any = this.parentView.context.question.userViewModel;
    this._UserInfoComponent_11_4.check_userObj(currVal_11_0_0,throwOnChange,false);
    const currVal_11_0_1:any = ((this.parentView.context.question == null)? (null as any): this.parentView.context.question.createdOn);
    this._UserInfoComponent_11_4.check_viewDate(currVal_11_0_1,throwOnChange,false);
    const currVal_11_0_2:any = ((this.parentView.context.question == null)? (null as any): this.parentView.context.question.isAnonymous);
    this._UserInfoComponent_11_4.check_isAnonymous(currVal_11_0_2,throwOnChange,false);
    this._UserInfoComponent_11_4.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_15_0_0:any = this.parentView.context.question;
    this._StatusComponent_15_5.check_questionObj(currVal_15_0_0,throwOnChange,false);
    const currVal_15_0_1:any = true;
    this._StatusComponent_15_5.check_isQuestion(currVal_15_0_1,throwOnChange,false);
    this._StatusComponent_15_5.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_18_0_0:any = ((this.parentView.context.question == null)? (null as any): this.parentView.context.question.id);
    this._CommentComponent_18_4.check_questionId(currVal_18_0_0,throwOnChange,false);
    const currVal_18_0_1:any = true;
    this._CommentComponent_18_4.check_isQuestion(currVal_18_0_1,throwOnChange,false);
    this._CommentComponent_18_4.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_61_0_0:any = this.parentView.context.question.answers;
    this._NgFor_61_6.check_ngForOf(currVal_61_0_0,throwOnChange,false);
    this._NgFor_61_6.ngDoCheck(this,this._anchor_61,throwOnChange);
    this._vc_61.detectChangesInNestedViews(throwOnChange);
    const currVal_79:any = import3.inlineInterpolate(1,'\n            ',this.parentView.context.question.title,'\n        ');
    if (import3.checkBinding(throwOnChange,this._expr_79,currVal_79)) {
      this.renderer.setText(this._text_7,currVal_79);
      this._expr_79 = currVal_79;
    }
    const currVal_80:any = this.parentView.context.question.body;
    if (import3.checkBinding(throwOnChange,this._expr_80,currVal_80)) {
      this.renderer.setElementProperty(this._el_13,'innerHTML',this.viewUtils.sanitizer.sanitize(import48.SecurityContext.HTML,currVal_80));
      this._expr_80 = currVal_80;
    }
    const currVal_81:any = import3.inlineInterpolate(1,'\n                ',((this.parentView.context.question.answers == null)? (null as any): this.parentView.context.question.answers.length),' ');
    if (import3.checkBinding(throwOnChange,this._expr_81,currVal_81)) {
      this.renderer.setText(this._text_30,currVal_81);
      this._expr_81 = currVal_81;
    }
    this.compView_4.internalDetectChanges(throwOnChange);
    this.compView_11.internalDetectChanges(throwOnChange);
    this.compView_15.internalDetectChanges(throwOnChange);
    this.compView_18.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_61.destroyNestedViews();
    this.compView_4.destroy();
    this.compView_11.destroy();
    this.compView_15.destroy();
    this.compView_18.destroy();
    this._StatusComponent_15_5.ngOnDestroy();
    this._CommentComponent_18_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 61)) { return new View_QuestionDetailComponent6(this.viewUtils,this,61,this._anchor_61,this._vc_61); }
    return (null as any);
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onQuestionDetailClicked')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onQuestionDetailClicked($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onQuestionReportClicked')) {
      const pd_sub_1:any = ((<any>this.parentView.context.onQuestionReportClicked($event,this.parentView.context.questionId,this.parentView.context.answerId)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.answerDialogBox(this.parentView.context.question)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_37(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.GetLatestAnswer(this.parentView.context.question.id)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_47(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.GetBestAnswer(this.parentView.context.question.id)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_QuestionDetailComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import16.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import18.Wrapper_NgIf;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_QuestionDetailComponent6,renderType_QuestionDetailComponent,import8.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import16.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import28.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import18.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import31.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.$implicit;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_QuestionDetailComponent7(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}
class View_QuestionDetailComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import34.UserInfoComponent>;
  _ProfileService_4_3:import35.ProfileService;
  _UserInfoComponent_4_4:import36.Wrapper_UserInfoComponent;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _NgClass_10_3:import49.Wrapper_NgClass;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  compView_16:import1.AppView<import37.StatusComponent>;
  _StatusService_16_3:import38.StatusService;
  _QuestionService_16_4:import23.QuestionService;
  _StatusComponent_16_5:import39.Wrapper_StatusComponent;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  compView_19:import1.AppView<import40.CommentComponent>;
  _CommentService_19_3:import41.CommentService;
  _CommentComponent_19_4:import42.Wrapper_CommentComponent;
  _text_20:any;
  _text_21:any;
  /*private*/ _expr_33:any;
  _map_34:any;
  /*private*/ _expr_35:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_QuestionDetailComponent7,renderType_QuestionDetailComponent,import8.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_33 = import44.UNINITIALIZED;
    this._map_34 = import3.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        enableFollowingImg: p0,
        disabledFollowingImg: p1
      }
      ;
    });
    this._expr_35 = import44.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','article-details'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'user-info',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_4 = new import36.View_UserInfoComponent0(this.viewUtils,this,4,this._el_4);
    this._ProfileService_4_3 = new import35.ProfileService(this.parentView.parentView.parentView.injectorGet(import11.Http,this.parentView.parentView.parentIndex));
    this._UserInfoComponent_4_4 = new import36.Wrapper_UserInfoComponent(this._ProfileService_4_3);
    this.compView_4.create(this._UserInfoComponent_4_4.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','pull-right'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                            ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'img',new import3.InlineArray2(2,'src','../../images/FollowingImage.svg'),(null as any));
    this._NgClass_10_3 = new import49.Wrapper_NgClass(this.parentView.parentView.parentView.injectorGet(import46.IterableDiffers,this.parentView.parentView.parentIndex),this.parentView.parentView.parentView.injectorGet(import50.KeyValueDiffers,this.parentView.parentView.parentIndex),new import51.ElementRef(this._el_10),this.renderer);
    this._text_11 = this.renderer.createText(this._el_8,'\n                        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_2,'p',new import3.InlineArray2(2,'class','answer-text'),(null as any));
    this._text_15 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_2,'ap-status',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_16 = new import39.View_StatusComponent0(this.viewUtils,this,16,this._el_16);
    this._StatusService_16_3 = new import38.StatusService(this.parentView.parentView.parentView.injectorGet(import11.Http,this.parentView.parentView.parentIndex));
    this._QuestionService_16_4 = new import23.QuestionService(this.parentView.parentView.parentView.injectorGet(import11.Http,this.parentView.parentView.parentIndex));
    this._StatusComponent_16_5 = new import39.Wrapper_StatusComponent(this.parentView.parentView.parentView.injectorGet(import14.ComponentFactoryResolver,this.parentView.parentView.parentIndex),this.parentView.parentView.parentView.injectorGet(import7.AuthenticationService,this.parentView.parentView.parentIndex),this._StatusService_16_3,this.parentView.parentView.parentView.injectorGet(import6.QuestionAnswerService,this.parentView.parentView.parentIndex),this.parentView.parentView.parentView.injectorGet(import29.CommunicationService,this.parentView.parentView.parentIndex),this._QuestionService_16_4,this.parentView.parentView.parentView.injectorGet(import45.ToastsManager,this.parentView.parentView.parentIndex));
    this._text_17 = this.renderer.createText((null as any),' ',(null as any));
    this.compView_16.create(this._StatusComponent_16_5.context);
    this._text_18 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_2,'ap-comment',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_19 = new import42.View_CommentComponent0(this.viewUtils,this,19,this._el_19);
    this._CommentService_19_3 = new import41.CommentService(this.parentView.parentView.parentView.injectorGet(import11.Http,this.parentView.parentView.parentIndex));
    this._CommentComponent_19_4 = new import42.Wrapper_CommentComponent(this._CommentService_19_3,this.parentView.parentView.parentView.injectorGet(import14.ComponentFactoryResolver,this.parentView.parentView.parentIndex),this.parentView.parentView.parentView.injectorGet(import29.CommunicationService,this.parentView.parentView.parentIndex));
    this.compView_19.create(this._CommentComponent_19_4.context);
    this._text_20 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._text_21 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_8));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_16,new import3.InlineArray2(2,'onQuestionReportClicked',(null as any)),this.eventHandler(this.handleEvent_16));
    this._StatusComponent_16_5.subscribe(this,this.eventHandler(this.handleEvent_16),false,true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import35.ProfileService) && (4 === requestNodeIndex))) { return this._ProfileService_4_3; }
    if (((token === import34.UserInfoComponent) && (4 === requestNodeIndex))) { return this._UserInfoComponent_4_4.context; }
    if (((token === import52.NgClass) && (10 === requestNodeIndex))) { return this._NgClass_10_3.context; }
    if (((token === import38.StatusService) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._StatusService_16_3; }
    if (((token === import23.QuestionService) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._QuestionService_16_4; }
    if (((token === import37.StatusComponent) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._StatusComponent_16_5.context; }
    if (((token === import41.CommentService) && (19 === requestNodeIndex))) { return this._CommentService_19_3; }
    if (((token === import40.CommentComponent) && (19 === requestNodeIndex))) { return this._CommentComponent_19_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4_0_0:any = ((this.parentView.context.$implicit == null)? (null as any): this.parentView.context.$implicit.userViewModel);
    this._UserInfoComponent_4_4.check_userObj(currVal_4_0_0,throwOnChange,false);
    const currVal_4_0_1:any = ((this.parentView.context.$implicit == null)? (null as any): this.parentView.context.$implicit.createdOn);
    this._UserInfoComponent_4_4.check_viewDate(currVal_4_0_1,throwOnChange,false);
    const currVal_4_0_2:any = ((this.parentView.context.$implicit == null)? (null as any): this.parentView.context.$implicit.isAnonymous);
    this._UserInfoComponent_4_4.check_isAnonymous(currVal_4_0_2,throwOnChange,false);
    this._UserInfoComponent_4_4.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_10_0_0:any = this._map_34(!((this.parentView.context.$implicit == null)? (null as any): this.parentView.context.$implicit.isFollowing),((this.parentView.context.$implicit == null)? (null as any): this.parentView.context.$implicit.isFollowing));
    this._NgClass_10_3.check_ngClass(currVal_10_0_0,throwOnChange,false);
    this._NgClass_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_16_0_0:any = this.parentView.parentView.parentView.context.question;
    this._StatusComponent_16_5.check_questionObj(currVal_16_0_0,throwOnChange,false);
    const currVal_16_0_1:any = this.parentView.context.$implicit;
    this._StatusComponent_16_5.check_answerObj(currVal_16_0_1,throwOnChange,false);
    const currVal_16_0_2:any = false;
    this._StatusComponent_16_5.check_isQuestion(currVal_16_0_2,throwOnChange,false);
    this._StatusComponent_16_5.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_19_0_0:any = ((this.parentView.parentView.parentView.context.question == null)? (null as any): this.parentView.parentView.parentView.context.question.id);
    this._CommentComponent_19_4.check_questionId(currVal_19_0_0,throwOnChange,false);
    const currVal_19_0_1:any = this.parentView.context.$implicit.id;
    this._CommentComponent_19_4.check_answerId(currVal_19_0_1,throwOnChange,false);
    const currVal_19_0_2:any = false;
    this._CommentComponent_19_4.check_isQuestion(currVal_19_0_2,throwOnChange,false);
    this._CommentComponent_19_4.ngDoCheck(this,this._el_19,throwOnChange);
    const currVal_33:any = import3.inlineInterpolate(1,'',((this.parentView.context.$implicit == null)? (null as any): this.parentView.context.$implicit.id),'');
    if (import3.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementProperty(this._el_2,'id',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_35:any = this.parentView.context.$implicit.text;
    if (import3.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementProperty(this._el_14,'innerHTML',this.viewUtils.sanitizer.sanitize(import48.SecurityContext.HTML,currVal_35));
      this._expr_35 = currVal_35;
    }
    this.compView_4.internalDetectChanges(throwOnChange);
    this.compView_16.internalDetectChanges(throwOnChange);
    this.compView_19.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_4.destroy();
    this.compView_16.destroy();
    this.compView_19.destroy();
    this._StatusComponent_16_5.ngOnDestroy();
    this._CommentComponent_19_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.parentView.context.QuestionFollowing(this.parentView.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onQuestionReportClicked')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.parentView.context.onQuestionReportClicked($event,this.parentView.parentView.parentView.context.questionId,this.parentView.parentView.parentView.context.answerId)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_QuestionDetailComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _NgForm_4_3:import53.Wrapper_NgForm;
  _ControlContainer_4_4:any;
  _NgControlStatusGroup_4_5:import54.Wrapper_NgControlStatusGroup;
  _text_5:any;
  _el_6:any;
  compView_6:import1.AppView<import32.QuestionHeaderComponent>;
  _QuestionHeaderComponent_6_3:import33.Wrapper_QuestionHeaderComponent;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _DefaultValueAccessor_10_3:import55.Wrapper_DefaultValueAccessor;
  _RequiredValidator_10_4:import56.Wrapper_RequiredValidator;
  _NG_VALIDATORS_10_5:any[];
  _NG_VALUE_ACCESSOR_10_6:any[];
  _NgModel_10_7:import57.Wrapper_NgModel;
  _NgControl_10_8:any;
  _NgControlStatus_10_9:import54.Wrapper_NgControlStatus;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _DefaultValueAccessor_17_3:import55.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_17_4:any[];
  _NgModel_17_5:import57.Wrapper_NgModel;
  _NgControl_17_6:any;
  _NgControlStatus_17_7:import54.Wrapper_NgControlStatus;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _map_49:any;
  /*private*/ _expr_50:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import16.ViewContainer) {
    super(View_QuestionDetailComponent8,renderType_QuestionDetailComponent,import8.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._map_49 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {standalone: p0};
    });
    this._expr_50 = import44.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','center-width center-body center-fix z-ground'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_4_3 = new import53.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_4_4 = this._NgForm_4_3.context;
    this._NgControlStatusGroup_4_5 = new import54.Wrapper_NgControlStatusGroup(this._ControlContainer_4_4);
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'question-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_6 = new import33.View_QuestionHeaderComponent0(this.viewUtils,this,6,this._el_6);
    this._QuestionHeaderComponent_6_3 = new import33.Wrapper_QuestionHeaderComponent(this.parentView.injectorGet(import12.Router,this.parentIndex));
    this.compView_6.create(this._QuestionHeaderComponent_6_3.context);
    this._text_7 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_4,'h1',new import3.InlineArray2(2,'class','question-title'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'input',new import3.InlineArray8(6,'name','editField','required','','style','width:538px;'),(null as any));
    this._DefaultValueAccessor_10_3 = new import55.Wrapper_DefaultValueAccessor(this.renderer,new import51.ElementRef(this._el_10));
    this._RequiredValidator_10_4 = new import56.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_10_5 = [this._RequiredValidator_10_4.context];
    this._NG_VALUE_ACCESSOR_10_6 = [this._DefaultValueAccessor_10_3.context];
    this._NgModel_10_7 = new import57.Wrapper_NgModel(this._ControlContainer_4_4,this._NG_VALIDATORS_10_5,(null as any),this._NG_VALUE_ACCESSOR_10_6);
    this._NgControl_10_8 = this._NgModel_10_7.context;
    this._NgControlStatus_10_9 = new import54.Wrapper_NgControlStatus(this._NgControl_10_8);
    this._text_11 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._text_12 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_4,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_4,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_4,'textarea',new import3.InlineArray16(10,'class','question-control','cols','86','name','editBody','placeholder','Agrega detalle de tu pregunta - Optional','rows','6'),(null as any));
    this._DefaultValueAccessor_17_3 = new import55.Wrapper_DefaultValueAccessor(this.renderer,new import51.ElementRef(this._el_17));
    this._NG_VALUE_ACCESSOR_17_4 = [this._DefaultValueAccessor_17_3.context];
    this._NgModel_17_5 = new import57.Wrapper_NgModel(this._ControlContainer_4_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_17_4);
    this._NgControl_17_6 = this._NgModel_17_5.context;
    this._NgControlStatus_17_7 = new import54.Wrapper_NgControlStatus(this._NgControl_17_6);
    this._text_18 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_4,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'button',new import3.InlineArray4(4,'class','btn btn-success fixed-height','type','submit'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n                    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_21,'\n                    Actualizar\n                ',(null as any));
    this._text_24 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_19,'button',new import3.InlineArray4(4,'class','btn btn-info fixed-height','type','button'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n                    ',(null as any));
    this._text_27 = this.renderer.createText(this._el_25,'\n                    Cancelar\n                ',(null as any));
    this._text_28 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._text_29 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_30 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_4));
    this._NgForm_4_3.subscribe(this,this.eventHandler(this.handleEvent_4),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_10));
    this._NgModel_10_7.subscribe(this,this.eventHandler(this.handleEvent_10),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_17,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_17));
    this._NgModel_17_5.subscribe(this,this.eventHandler(this.handleEvent_17),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_25,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_25));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.QuestionHeaderComponent) && (6 === requestNodeIndex))) { return this._QuestionHeaderComponent_6_3.context; }
    if (((token === import58.DefaultValueAccessor) && (10 === requestNodeIndex))) { return this._DefaultValueAccessor_10_3.context; }
    if (((token === import59.RequiredValidator) && (10 === requestNodeIndex))) { return this._RequiredValidator_10_4.context; }
    if (((token === import60.NG_VALIDATORS) && (10 === requestNodeIndex))) { return this._NG_VALIDATORS_10_5; }
    if (((token === import61.NG_VALUE_ACCESSOR) && (10 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_10_6; }
    if (((token === import62.NgModel) && (10 === requestNodeIndex))) { return this._NgModel_10_7.context; }
    if (((token === import63.NgControl) && (10 === requestNodeIndex))) { return this._NgControl_10_8; }
    if (((token === import64.NgControlStatus) && (10 === requestNodeIndex))) { return this._NgControlStatus_10_9.context; }
    if (((token === import58.DefaultValueAccessor) && (17 === requestNodeIndex))) { return this._DefaultValueAccessor_17_3.context; }
    if (((token === import61.NG_VALUE_ACCESSOR) && (17 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_17_4; }
    if (((token === import62.NgModel) && (17 === requestNodeIndex))) { return this._NgModel_17_5.context; }
    if (((token === import63.NgControl) && (17 === requestNodeIndex))) { return this._NgControl_17_6; }
    if (((token === import64.NgControlStatus) && (17 === requestNodeIndex))) { return this._NgControlStatus_17_7.context; }
    if (((token === import65.NgForm) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._NgForm_4_3.context; }
    if (((token === import66.ControlContainer) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._ControlContainer_4_4; }
    if (((token === import64.NgControlStatusGroup) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._NgControlStatusGroup_4_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this._NgControlStatusGroup_4_5.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_6_0_0:any = this.parentView.context.question;
    this._QuestionHeaderComponent_6_3.check_question(currVal_6_0_0,throwOnChange,false);
    this._QuestionHeaderComponent_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    this._DefaultValueAccessor_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_1_0:any = '';
    this._RequiredValidator_10_4.check_required(currVal_10_1_0,throwOnChange,false);
    this._RequiredValidator_10_4.ngDoCheck(this,this._el_10,throwOnChange);
    const currVal_10_2_0:any = 'editField';
    this._NgModel_10_7.check_name(currVal_10_2_0,throwOnChange,false);
    const currVal_10_2_1:any = this.parentView.context.editTitle;
    this._NgModel_10_7.check_model(currVal_10_2_1,throwOnChange,false);
    this._NgModel_10_7.ngDoCheck(this,this._el_10,throwOnChange);
    this._NgControlStatus_10_9.ngDoCheck(this,this._el_10,throwOnChange);
    this._DefaultValueAccessor_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    const currVal_17_1_0:any = 'editBody';
    this._NgModel_17_5.check_name(currVal_17_1_0,throwOnChange,false);
    const currVal_17_1_1:any = this.parentView.context.editBody;
    this._NgModel_17_5.check_model(currVal_17_1_1,throwOnChange,false);
    const currVal_17_1_2:any = this._map_49(true);
    this._NgModel_17_5.check_options(currVal_17_1_2,throwOnChange,false);
    this._NgModel_17_5.ngDoCheck(this,this._el_17,throwOnChange);
    this._NgControlStatus_17_7.ngDoCheck(this,this._el_17,throwOnChange);
    this._NgControlStatusGroup_4_5.checkHost(this,this,this._el_4,throwOnChange);
    this._RequiredValidator_10_4.checkHost(this,this,this._el_10,throwOnChange);
    this._NgControlStatus_10_9.checkHost(this,this,this._el_10,throwOnChange);
    this._NgControlStatus_17_7.checkHost(this,this,this._el_17,throwOnChange);
    const currVal_50:boolean = !this._NgForm_4_3.context.form.valid;
    if (import3.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementProperty(this._el_21,'disabled',currVal_50);
      this._expr_50 = currVal_50;
    }
    this.compView_6.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_6.destroy();
    this._NgModel_10_7.ngOnDestroy();
    this._NgModel_17_5.ngOnDestroy();
    this._NgForm_4_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_4_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.context.updateQuestion()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_10_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.editTitle = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_17(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_17_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.editBody = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_25(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onQuestionDetailClicked(false)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}