/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './apbanner.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/linker/element_ref';
import * as import9 from '../../services/window-ref.service';
import * as import10 from './carousel.css.shim.ngstyle';
import * as import11 from '@angular/core/src/change_detection/change_detection_util';
import * as import12 from '@angular/core/src/security';
export class Wrapper_ApBannerComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ApBannerComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.ApBannerComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    if ((eventName == 'window:scroll')) {
      const pd_sub_0:any = ((<any>this.context.track($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ApBannerComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ApBannerComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ApBannerComponent>;
  _ApBannerComponent_0_3:Wrapper_ApBannerComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ApBannerComponent_Host0,renderType_ApBannerComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ap-banner',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ApBannerComponent0(this.viewUtils,this,0,this._el_0);
    this._ApBannerComponent_0_3 = new Wrapper_ApBannerComponent(new import8.ElementRef(this._el_0),this.injectorGet(import9.WindowRefService,this.parentIndex));
    this.compView_0.create(this._ApBannerComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'scroll','window'),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ApBannerComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ApBannerComponent) && (0 === requestNodeIndex))) { return this._ApBannerComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ApBannerComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._ApBannerComponent_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
export const ApBannerComponentNgFactory:import7.ComponentFactory<import0.ApBannerComponent> = new import7.ComponentFactory<import0.ApBannerComponent>('ap-banner',View_ApBannerComponent_Host0,import0.ApBannerComponent);
const styles_ApBannerComponent:any[] = [import10.styles];
var renderType_ApBannerComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_ApBannerComponent,{});
export class View_ApBannerComponent0 extends import1.AppView<import0.ApBannerComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  /*private*/ _expr_27:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ApBannerComponent0,renderType_ApBannerComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_27 = import11.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','carousel'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'ul',new import3.InlineArray2(2,'class','slides'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'li',new import3.InlineArray2(2,'class','slide-item'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'img',new import3.InlineArray4(4,'alt','background','class','background-img'),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','banner-text'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Pregunta y comparte tu ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'conocimiento',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,' ',(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','banner-arrow-container'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'sobre negocios\n                    ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'img',new import3.InlineArray8(6,'alt','arrow','class','banner-arrow','src','../images/curved-arrow.png'),(null as any));
    this._text_19 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._text_20 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_8,'a',new import3.InlineArray4(4,'class','btn-banner','href','http://altaperspectiva.com/conocemas'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Conoce más',(null as any));
    this._text_23 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._text_24 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_27:any = import3.inlineInterpolate(1,'',this.context.images[0].url,'');
    if (import3.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import12.SecurityContext.URL,currVal_27));
      this._expr_27 = currVal_27;
    }
  }
}