/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../../tsScripts/app/dashboard/viewprofile/edit-profile/add-employment.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '../../../../../../tsScripts/app/services/profile.service';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/http/src/http';
import * as import10 from '../../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import11 from '../../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from '../../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import13 from '../../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import14 from '../../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import15 from '@angular/core/src/change_detection/change_detection_util';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/forms/src/directives/default_value_accessor';
import * as import18 from '@angular/forms/src/directives/validators';
import * as import19 from '@angular/forms/src/validators';
import * as import20 from '@angular/forms/src/directives/control_value_accessor';
import * as import21 from '@angular/forms/src/directives/ng_model';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/ng_control_status';
import * as import24 from '@angular/forms/src/directives/ng_form';
import * as import25 from '@angular/forms/src/directives/control_container';
export class Wrapper_AddEmploymentComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AddEmploymentComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.AddEmploymentComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AddEmploymentComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AddEmploymentComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AddEmploymentComponent>;
  _ProfileService_0_3:import5.ProfileService;
  _AddEmploymentComponent_0_4:Wrapper_AddEmploymentComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AddEmploymentComponent_Host0,renderType_AddEmploymentComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'add-employment',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AddEmploymentComponent0(this.viewUtils,this,0,this._el_0);
    this._ProfileService_0_3 = new import5.ProfileService(this.injectorGet(import9.Http,this.parentIndex));
    this._AddEmploymentComponent_0_4 = new Wrapper_AddEmploymentComponent(this._ProfileService_0_3);
    this.compView_0.create(this._AddEmploymentComponent_0_4.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._AddEmploymentComponent_0_4.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import5.ProfileService) && (0 === requestNodeIndex))) { return this._ProfileService_0_3; }
    if (((token === import0.AddEmploymentComponent) && (0 === requestNodeIndex))) { return this._AddEmploymentComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AddEmploymentComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AddEmploymentComponentNgFactory:import8.ComponentFactory<import0.AddEmploymentComponent> = new import8.ComponentFactory<import0.AddEmploymentComponent>('add-employment',View_AddEmploymentComponent_Host0,import0.AddEmploymentComponent);
const styles_AddEmploymentComponent:any[] = ['.credential-dialog[_ngcontent-%COMP%] {\n        margin: 10% auto;\n        max-width: 45%;\n    }\n\n    .profile-modal-body[_ngcontent-%COMP%] {\n        position: relative;\n        padding: 15px;\n        background-color: #f6f6f6;\n        margin: 0px;\n        border-bottom-left-radius: 5px;\n        border-bottom-right-radius: 5px;\n    }\n\n        .profile-modal-body[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] {\n            width: 100%;\n            border: 1px solid #bdbdbd;\n            border-radius: 3px;\n            padding: 2px 5px;\n            margin-top: 5px;\n            margin-bottom: 5px;\n        }\n\n        .profile-modal-body[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover {\n            text-decoration: underline;\n        }\n\n    .profile-modal-button-container[_ngcontent-%COMP%] {\n        text-align: right;\n    }\n\n        .profile-modal-button-container[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n            margin-right: 10px;\n        }\n\n    .modal-header[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] {\n        font-weight: bold;\n    }\n     .col-sm-8[_ngcontent-%COMP%] {\n        padding-left: 0;\n    }'];
var renderType_AddEmploymentComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_AddEmploymentComponent,{});
export class View_AddEmploymentComponent0 extends import1.AppView<import0.AddEmploymentComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _NgForm_19_3:import10.Wrapper_NgForm;
  _ControlContainer_19_4:any;
  _NgControlStatusGroup_19_5:import11.Wrapper_NgControlStatusGroup;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _DefaultValueAccessor_28_3:import12.Wrapper_DefaultValueAccessor;
  _RequiredValidator_28_4:import13.Wrapper_RequiredValidator;
  _NG_VALIDATORS_28_5:any[];
  _NG_VALUE_ACCESSOR_28_6:any[];
  _NgModel_28_7:import14.Wrapper_NgModel;
  _NgControl_28_8:any;
  _NgControlStatus_28_9:import11.Wrapper_NgControlStatus;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _DefaultValueAccessor_42_3:import12.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_42_4:any[];
  _NgModel_42_5:import14.Wrapper_NgModel;
  _NgControl_42_6:any;
  _NgControlStatus_42_7:import11.Wrapper_NgControlStatus;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  /*private*/ _expr_78:any;
  _map_79:any;
  /*private*/ _expr_80:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AddEmploymentComponent0,renderType_AddEmploymentComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_78 = import15.UNINITIALIZED;
    this._map_79 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {standalone: p0};
    });
    this._expr_80 = import15.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','modal-overlay z-modal','id','dialogModal'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','modal-content credential-dialog'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray2(2,'class','exit-button'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'x',(null as any));
    this._text_7 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_3,'div',new import3.InlineArray4(4,'class','modal-container','style','border:1px solid;'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','modal-header'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Información de trabajo',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._text_15 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._text_16 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','profile-modal-body'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'form',new import3.InlineArray2(2,'class','form-horizontal'),(null as any));
    this._NgForm_19_3 = new import10.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_19_4 = this._NgForm_19_3.context;
    this._NgControlStatusGroup_19_5 = new import11.Wrapper_NgControlStatusGroup(this._ControlContainer_19_4);
    this._text_20 = this.renderer.createText(this._el_19,'\n                    ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n                        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'label',new import3.InlineArray4(4,'class','control-label col-sm-4','for','email'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Cargo* :',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n                        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_21,'div',new import3.InlineArray2(2,'class','col-sm-8'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n                            ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'input',new import3.InlineArray16(12,'class','form-control','id','position','name','position','placeholder','¿Qué haces?','required','','type','text'),(null as any));
    this._DefaultValueAccessor_28_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_28));
    this._RequiredValidator_28_4 = new import13.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_28_5 = [this._RequiredValidator_28_4.context];
    this._NG_VALUE_ACCESSOR_28_6 = [this._DefaultValueAccessor_28_3.context];
    this._NgModel_28_7 = new import14.Wrapper_NgModel(this._ControlContainer_19_4,this._NG_VALIDATORS_28_5,(null as any),this._NG_VALUE_ACCESSOR_28_6);
    this._NgControl_28_8 = this._NgModel_28_7.context;
    this._NgControlStatus_28_9 = new import11.Wrapper_NgControlStatus(this._NgControl_28_8);
    this._text_29 = this.renderer.createText(this._el_26,'\n                            ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_26,'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n                                Es requerido\n                            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_26,'\n                         ',(null as any));
    this._text_33 = this.renderer.createText(this._el_21,'\n                    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_19,'\n                    ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'label',new import3.InlineArray4(4,'class','control-label col-sm-4','for','pwd'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Nombre empresa:',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_35,'div',new import3.InlineArray2(2,'class','col-sm-8'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                            ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'input',new import3.InlineArray8(8,'class','form-control','id','CompanyName','placeholder','¿Dónde laboras?','type','text'),(null as any));
    this._DefaultValueAccessor_42_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_42));
    this._NG_VALUE_ACCESSOR_42_4 = [this._DefaultValueAccessor_42_3.context];
    this._NgModel_42_5 = new import14.Wrapper_NgModel(this._ControlContainer_19_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_42_4);
    this._NgControl_42_6 = this._NgModel_42_5.context;
    this._NgControlStatus_42_7 = new import11.Wrapper_NgControlStatus(this._NgControl_42_6);
    this._text_43 = this.renderer.createText(this._el_40,'\n                        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._text_45 = this.renderer.createText(this._el_19,'\n\n                    ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','profile-modal-button-container'),(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'\n                        ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Eliminar',(null as any));
    this._text_50 = this.renderer.createText(this._el_46,'\n                        ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_46,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_52 = this.renderer.createText(this._el_51,' Cancelar',(null as any));
    this._text_53 = this.renderer.createText(this._el_46,'\n                        ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_46,'button',new import3.InlineArray4(4,'class','btn btn-success','type','submit'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'Guardar',(null as any));
    this._text_56 = this.renderer.createText(this._el_46,'\n                    ',(null as any));
    this._text_57 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._text_58 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._text_59 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_60 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_61 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_62 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_5));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_19,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_19));
    this._NgForm_19_3.subscribe(this,this.eventHandler(this.handleEvent_19),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_28,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_28));
    this._NgModel_28_7.subscribe(this,this.eventHandler(this.handleEvent_28),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_42,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_42));
    this._NgModel_42_5.subscribe(this,this.eventHandler(this.handleEvent_42),true);
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_48,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_48));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_51,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_51));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.DefaultValueAccessor) && (28 === requestNodeIndex))) { return this._DefaultValueAccessor_28_3.context; }
    if (((token === import18.RequiredValidator) && (28 === requestNodeIndex))) { return this._RequiredValidator_28_4.context; }
    if (((token === import19.NG_VALIDATORS) && (28 === requestNodeIndex))) { return this._NG_VALIDATORS_28_5; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (28 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_28_6; }
    if (((token === import21.NgModel) && (28 === requestNodeIndex))) { return this._NgModel_28_7.context; }
    if (((token === import22.NgControl) && (28 === requestNodeIndex))) { return this._NgControl_28_8; }
    if (((token === import23.NgControlStatus) && (28 === requestNodeIndex))) { return this._NgControlStatus_28_9.context; }
    if (((token === import17.DefaultValueAccessor) && (42 === requestNodeIndex))) { return this._DefaultValueAccessor_42_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (42 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_42_4; }
    if (((token === import21.NgModel) && (42 === requestNodeIndex))) { return this._NgModel_42_5.context; }
    if (((token === import22.NgControl) && (42 === requestNodeIndex))) { return this._NgControl_42_6; }
    if (((token === import23.NgControlStatus) && (42 === requestNodeIndex))) { return this._NgControlStatus_42_7.context; }
    if (((token === import24.NgForm) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._NgForm_19_3.context; }
    if (((token === import25.ControlContainer) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._ControlContainer_19_4; }
    if (((token === import23.NgControlStatusGroup) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._NgControlStatusGroup_19_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_19_3.ngDoCheck(this,this._el_19,throwOnChange);
    this._NgControlStatusGroup_19_5.ngDoCheck(this,this._el_19,throwOnChange);
    this._DefaultValueAccessor_28_3.ngDoCheck(this,this._el_28,throwOnChange);
    const currVal_28_1_0:any = '';
    this._RequiredValidator_28_4.check_required(currVal_28_1_0,throwOnChange,false);
    this._RequiredValidator_28_4.ngDoCheck(this,this._el_28,throwOnChange);
    const currVal_28_2_0:any = 'position';
    this._NgModel_28_7.check_name(currVal_28_2_0,throwOnChange,false);
    const currVal_28_2_1:any = this.context.employment.position;
    this._NgModel_28_7.check_model(currVal_28_2_1,throwOnChange,false);
    this._NgModel_28_7.ngDoCheck(this,this._el_28,throwOnChange);
    this._NgControlStatus_28_9.ngDoCheck(this,this._el_28,throwOnChange);
    this._DefaultValueAccessor_42_3.ngDoCheck(this,this._el_42,throwOnChange);
    const currVal_42_1_0:any = this.context.employment.companyName;
    this._NgModel_42_5.check_model(currVal_42_1_0,throwOnChange,false);
    const currVal_42_1_1:any = this._map_79(true);
    this._NgModel_42_5.check_options(currVal_42_1_1,throwOnChange,false);
    this._NgModel_42_5.ngDoCheck(this,this._el_42,throwOnChange);
    this._NgControlStatus_42_7.ngDoCheck(this,this._el_42,throwOnChange);
    this._NgControlStatusGroup_19_5.checkHost(this,this,this._el_19,throwOnChange);
    this._RequiredValidator_28_4.checkHost(this,this,this._el_28,throwOnChange);
    this._NgControlStatus_28_9.checkHost(this,this,this._el_28,throwOnChange);
    const currVal_78:any = (this._NgModel_28_7.context.valid || this._NgModel_28_7.context.pristine);
    if (import3.checkBinding(throwOnChange,this._expr_78,currVal_78)) {
      this.renderer.setElementProperty(this._el_30,'hidden',currVal_78);
      this._expr_78 = currVal_78;
    }
    this._NgControlStatus_42_7.checkHost(this,this,this._el_42,throwOnChange);
    const currVal_80:boolean = !this._NgForm_19_3.context.form.valid;
    if (import3.checkBinding(throwOnChange,this._expr_80,currVal_80)) {
      this.renderer.setElementProperty(this._el_54,'disabled',currVal_80);
      this._expr_80 = currVal_80;
    }
  }
  destroyInternal():void {
    this._NgModel_28_7.ngOnDestroy();
    this._NgModel_42_5.ngOnDestroy();
    this._NgForm_19_3.ngOnDestroy();
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.handleClick($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickedExit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_19_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.onEmploymentSubmit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_28(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_28_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.employment.position = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_42(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_42_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.employment.companyName = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_48(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.DeleteEmployment()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_51(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClickedExit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}